eclipse-zenoh/zenoh-c

rust-toolchain
src/lib.rs
src/net/mod.rs
src/net/types.rs

Compile with stable rust by replicating the functionality in unstable for into_raw_parts
Signed-off-by: Tom Burdick <thomas.burdick@gmail.com>

Compile with rust stable

---

src/net/types.rs

The field was renamed in https://github.com/eclipse-zenoh/zenoh/commit/922b900655df1731fd82c5cc47ae6ab3c38e3d55.

The `Reply.source_kind` field was renamed to `replier_kind`

---

.github/workflows/release.yml

Cross-platform release was failing because cargo-deb couldn't find the appropriate strip command.
I guess this stripping was added (somewhat) recently, breaking our releases. For now I disabled stripping (it wasn't happening before anyway), and we can try to strip again later if we find it relevant.

add --no-strip to cargo-deb so that it doesn't try (and fail) to strip cross-compiled artifacts

---

Cargo.lock
docs/examples.rst
examples/z_get.c
include/zenoh_commons.h
src/types.rs

Following eclipse-zenoh/zenoh#233, in struct:
```C
typedef struct z_owned_reply_data_t {
struct z_owned_sample_t data;
unsigned int source_kind;
struct z_owned_bytes_t replier_id;
} z_owned_reply_data_t;
```
this PR renames the `data` attribute as `sample`.

Rename z_owned_reply_data_t.data as z_owned_reply_data_t.sample

---

CMakeLists.txt
Cargo.toml
Cargo.toml.in
README.md
examples/z_get.c
examples/z_info.c
examples/z_non_blocking_get.c
examples/z_pub.c
examples/z_pub_thr.c
examples/z_pull.c
examples/z_put.c
examples/z_queryable.c
examples/z_scout.c
examples/z_sub.c
examples/z_sub_thr.c
include/zenoh_commons.h
src/lib.rs
src/scouting.rs
src/session.rs

A feature flag allows to build zenoh-c without the auto init.
~WIP: need to expose the feature flag through cmake.~
I think this PR is ready and would be useful to users who want to disable logs, without forcing everyone to enable them manually.

auto-init the logger for easier zc-zp compat

---

Cargo.lock
Cargo.toml
Cargo.toml.in

This is a preparatory PR. 
It will be merged once https://github.com/eclipse-zenoh/zenoh/pull/347 is merged and `Cargo.lock` is synced.

Point to master branch

---

build.rs
include/zenoh.h
include/zenoh_commons.h
src/get.rs

From what I read, the `u128` is aligned to 8 bytes is more of an x86 specificity than the opposite as we thought.

fix layouts for non x86 platforms

---

Cargo.lock
include/zenoh_macros.h
tests/z_api_null_drop_test.c

- missing macroses for z_hello_owned_t added
- Cargo.lock updated to latest zenoh, primarily to pull the fix for scouting bug https://github.com/eclipse-zenoh/zenoh/pull/387

macroses for z_hello_owned_t added

---

include/zenoh_concrete.h
src/get.rs

@cguimaraes Learning experience: for these tricky things, be careful not to represent u128 as 2*usize, as that only works on 64bit targets. Use `_z_u128` instead, which is defined in the C headers to have the right size and alignment (C doesn't have a standard u128 T-T)

Fix SourceInfo layout in z_owned_reply_t

---

include/zenoh.h

Use _uint128_t type if it's avaialble, check real type size on compilation stage

128-bit type fix for apple clang and MSVC compilers

---

PackageConfig.cmake.in

Closes #111, resolves eclipse-zenoh/zenoh-cpp#7.
In short: this enables zenoh-cpp (which depends on files generated by zenoh-c compilation) to be compiled on Ubuntu 20.04 with the default CMake 3.16.

added GLOBAL to 2 add_library functions

---

.gitignore
build.rs
include/zenoh.h

Fix for issue https://github.com/eclipse-zenoh/zenoh-c/issues/116

Select alignment for 128-bit integer for C the same as in Rust

---

CMakeLists.txt
include/zenoh_commons.h
src/keyexpr.rs

- updated definition of z_keyexpr_t to make it explicitly crossplatform
- added cross compilation test for build on all supported CPU architectures. To run this test:
install necessary packages and rustup targets for cross compilation
```
sudo apt install gcc-arm-linux-gnueabi
sudo apt install gcc-x86-64-linux-gnu
sudo apt install gcc-aarch64-linux-gnu
rustup target add arm-unknown-linux-gnueabi
rustup target add aarch64-unknown-linux-gnu
rustup target add x86_64-unknown-linux-gnu
```
and run test itself
```
mkdir build && cd build && cmake ..
cmake --build . --target crosscheck
```
`crosscheck` test works on Ubuntu at this moment. Need to be investigated how to make this cross compilation in MacOS

z_keyexpr_t guarded transmute, cross-build check in cmake

---

build.rs
include/zenoh.h

Selection of cpu architecture incorrectly used comparison operator in C preprocessor which actually works for integer values only: https://c-faq.com/cpp/ifstrcmp.html

removed sring comparison in preprocessor

---

.github/workflows/ci.yml
include/zenoh_commons.h
src/collections.rs
src/scouting.rs

This change is necessary for zenoh-cpp in initializers like { .val = xxx, .len = yyy }, which are sensitive to field order.
Also corrected github .ci test for building examples from installed package

fields order made same as zenoh-pico

---

Cargo.toml.in

The Cargo.toml is being overwritten each time when CMake build is performed from the template file Cargo.toml.in. So both files should be updated.
Maybe we should consider removing Cargo.toml from repository to avoid mistakes. On the other hand immediate availability of it can be convenient if customer wants to make build with Rust tools only

true source Cargo.toml.in updated

---

examples/z_get.c
include/zenoh_commons.h
src/get.rs

Field "with_value" in C API was mistakenly named. The name was copied from rust's function 'with_value' which is actually Rust's 'builder pattern' approach to set 'value' property. So the actual property name should be 'value', like in original Rust code.

replace with_value to just value

---

examples/CMakeLists.txt
examples/z_ping.c
examples/z_pong.c

As requested by @Mallets, I wrote this example in the same "channel" style as the rust examples.
Because zenoh-c doesn't have the same abstractions over mutex/cond_var as zenoh-pico, I can't make it cross-platform without adding a lot of noise.

added ping/pong examples (posix only)

---

CMakeLists.txt
Cargo.lock
Cargo.toml
Cargo.toml.in
examples/z_ping.c
examples/z_pong.c
examples/z_pub_shm.c
include/zenoh_commons.h
include/zenoh_macros.h
src/commons.rs
src/get.rs
src/lib.rs
src/publisher.rs
src/pull_subscriber.rs
src/put.rs
src/shm.rs
src/subscriber.rs
tests/z_api_null_drop_test.c

Zenoh has been SHM-capable for a while. With this, so will Zenoh-C.
Review goals:
- check for bugs, of course
- _evaluate API choices_: I'm very open to better names for `zc_sample_rcinc`, with the goal of keeping the lack of copy explicit

Introduce shared memory to Zenoh-C

---

examples/z_pub_shm.c
include/zenoh_commons.h
include/zenoh_concrete.h
src/get.rs
src/info.rs
src/keyexpr.rs
src/publisher.rs
src/pull_subscriber.rs
src/put.rs
src/queryable.rs
src/session.rs
src/subscriber.rs

With this, `z_owned_session_t` (`Option<Arc<Session>>`) is always movable, even when aliased by a `z_session_t` (`Option<Weak<Session>>`).

make session refcounted

---

src/publisher.rs
tests/z_api_keyexpr_drop_test.c

Fix for bug https://github.com/eclipse-zenoh/zenoh-c/issues/160
Probably issue is related not to Publisher only, the Queryable, Subscriber, etc, may have same problem, PR to be updated

Keyexpr drop

---

include/zenoh_commons.h
include/zenoh_macros.h
src/publisher.rs
src/pull_subscriber.rs
src/subscriber.rs
tests/z_api_keyexpr_drop_test.c

this also allowed to make correct test for https://github.com/eclipse-zenoh/zenoh-c/issues/160

`keyexpr` methods of subscriber and publisher made available in C interface

---

include/zenoh_macros.h

minor followup to https://github.com/eclipse-zenoh/zenoh-c/pull/162 - `z_loan` template for C++ equal to exisitng C macro

z_loan for z_owned_subscriber_t

---

CMakeLists.txt
Cargo.toml
Cargo.toml.in

updates to make release 0.7.2 compilable: added references to zenoh-0.7.2 to Cargo.toml.in instead of autogenerated Cargo.toml.
This PR is not supposed to be merged, I think: the updates can be just kept in this `release-0.7.2-rc.1` branch

updated zenoh version info in Cargo.toml.in

---

.github/workflows/ci.yml
CMakeLists.txt
build.rs
cbindgen.toml
include/zenoh.h
include/zenoh_commons.h
install/CMakeLists.txt
install/PackageConfig.cmake.in
tests/z_api_constants.c

Fix for https://github.com/eclipse-zenoh/zenoh-c/issues/165 issue.
Without `__declspec(dllimport)` the `extern const ....` values are mapped incorrectly when linked to dll import library, without any diagnostics

__declspec(dllimport) added to headers for windows

---

README.md

While modifying the z_ping examples on #184, I noticed some typos on the Readme.

Remove typos from readme

---

examples/z_ping.c

We detected an issue in zenoh-pico where z_ping example was using cpu time instead of wall time for measurements and this one had it too.
Also harmonized the default arg values to be more consistence across implementations.
Note that the measurements seems too good to be true (rtt ~13µs) on my machine although more realistic than the ones measured without the changes (rtt ~4µs).

Use wall time in z_ping example.

---

examples/z_get_liveliness.c
examples/z_liveliness.c
examples/z_sub_liveliness.c
include/zenoh_commons.h
include/zenoh_macros.h
src/lib.rs
src/liveliness.rs

Add the liveliness methods bindings:
- zc_liveliness_declaration_options_check
- zc_liveliness_declaration_options_drop
- zc_liveliness_declaration_options_null
- zc_liveliness_declare_subscriber
- zc_liveliness_declare_token
- zc_liveliness_get
- zc_liveliness_get_options_check
- zc_liveliness_get_options_default
- zc_liveliness_get_options_drop
- zc_liveliness_get_options_null
- zc_liveliness_subscriber_options_check
- zc_liveliness_subscriber_options_drop
- zc_liveliness_subscriber_options_null
- zc_liveliness_token_check
- zc_liveliness_token_null
- zc_liveliness_undeclare_token
Along with the examples:
- z_sub_liveliness
- z_get_liveliness

Add liveliness bindings

---

include/zenoh_commons.h
src/pull_subscriber.rs
src/put.rs
src/subscriber.rs

Changes options processing from pointer to Option in the functions:
- z_declare_pull_subscriber
- z_declare_subscriber
- z_put
- zc_put_owned
- z_delete
Benefites:
- Consistence with other options processing (e.g. z_declare_publisher, z_declare_queryable, etc.)
- Avoid unnecessary unsafe code
Additionally removes unrelevant comments from z_declare_subscriber and z_declare_pull_subscriber

Options processing refactoring

---

Cargo.lock
Cargo.toml
Cargo.toml.in
docs/api.rst
examples/z_pub_cache.c
examples/z_query_sub.c
include/zenoh_commons.h
include/zenoh_macros.h
src/commons.rs
src/config.rs
src/lib.rs
src/publication_cache.rs
src/querying_subscriber.rs
tests/z_api_constants.c

**Add publication cache and querying subscriber C bindings**
For publication cache:
- ze_declare_publication_cache
- ze_undeclare_publication_cache
- ze_publication_cache_check
- ze_publication_cache_null
- ze_publication_cache_options_default
For querying subscriber:
- ze_declare_querying_subscriber
- ze_undeclare_querying_subscriber
- ze_querying_subscriber_check
- ze_querying_subscriber_null
- ze_querying_subscriber_options_default
Additionally provided bindings for required but unstable types:
- zcu_locality_t
- zcu_reply_keyexpr_t
Usage examples:
- z_pub_cache.c
- z_query_sub.c
Value of Z_CONFIG_ADD_TIMESTAMP_KEY changed to the actual one.

Add publication cache and querying subscriber

---

docs/api.rst
include/zenoh_commons.h
src/liveliness.rs

Add liveliness documentation configuration plus some documentation enhancement and fixes.

Add liveliness documentation

---

include/zenoh_macros.h

Add the missed c++ API bindings
- z_drop
- z_null
for the types:
- zc_owned_liveliness_token_t
- ze_owned_publication_cache_t
- ze_owned_querying_subscriber_t
(z_check was fixed by https://github.com/eclipse-zenoh/zenoh-c/pull/195)

Add missed c++ API bindings

---

examples/z_pub_shm.c
examples/z_sub.c

Shared memory needs to be explicitly activated in the configuration in order to be operational.
This is not the case in the examples provided in zenoh-c.
Therefore, this PR enables shared-memory in shared-memory examples.

Enable shared-memory in shared-memory examples

---

Cargo.lock
docs/api.rst
include/zenoh_commons.h
include/zenoh_macros.h
src/querying_subscriber.rs

Add ze_querying_subscriber_get method as wrapper for FetchingSubscriber fetch with the default behavior: "get by specified selector".
Currently contains workaround with saved session, which must be removed as soon as new fetch method will be implemented in zenoh.
Testing:
- modify z_query_sub example to call the queryable:
add `ze_querying_subscriber_get(z_loan(sub), z_keyexpr("demo/example/zenoh-c-queryable"), NULL);` to the input check loop.
- run z_pub_cache example
- run z_queryable example
- run z_query_sub and press some key periodically
- check if z_query_sub receives the data from z_queryable

Add ze_querying_subscriber_get method

---

CMakeLists.txt

This command line allows to perform cross-compilation on arm for x86_64:
```
cmake -S zenoh-c -B build -DZENOHC_CUSTOM_TARGET=x86_64-unknown-linux-gnu -DZENOHC_CARGO_FLAGS="--config target.x86_64-unknown-linux-gnu.linker=\"/usr/bin/x86_64-linux-gnu-gcc\""
```
It fails without the `VERBATIM` option in CMake's `add_custom_command`. Without this option the quotes around path to linker are incorrectly removed.
After adding `VERBATIM` compilation started to fail on multiconfig-builders (MSVC, Ninja Multi-Config), so this also was fixed.

allow to pass quoted parameters to rust

---

include/zenoh_macros.h

Adds missing explicit template instantiation for loaning the `z_owned_query_t`
Follow-up PR from https://github.com/eclipse-zenoh/zenoh-c/pull/213

Adds missing zenoh_loan_type explicit instanciation for query.

---

Cargo.lock
docs/api.rst
examples/z_pub_attachment.c
examples/z_put.c
examples/z_sub_attachment.c
include/zenoh_commons.h
include/zenoh_macros.h
src/attachment.rs
src/collections.rs
src/commons.rs
src/get.rs
src/lib.rs
src/publisher.rs
src/put.rs
src/queryable.rs
tests/z_api_attachment_test.c
tests/z_int_pub_sub_attachment_test.c
tests/z_int_queryable_attachment_test.c

Implement [attachment api](https://github.com/eclipse-zenoh/zenoh/pull/613) support "C" binding
Allows add attachment to pub/sub/query/reply.
Expands z_bytes_t with methods:
- z_bytes_new
- z_bytes_null
Adds z_owned_bytes_map_t:
- z_bytes_map_new
- z_bytes_map_check
- z_bytes_map_null
- z_bytes_map_drop
- z_bytes_map_get
- z_bytes_map_insert_by_alias
- z_bytes_map_insert_by_copy
- z_bytes_map_iter
- z_bytes_map_from_attachment
- z_bytes_map_from_attachment_aliasing
Adds method to the z_query_t:
- z_query_attachment
Adds z_attachment_t:
- z_attachment_null
- z_attachment_get
- z_attachment_check
- z_attachment_iterate
Adds samples:
- z_pub_attachment.c
- z_sub_attachment.c
Adds tests:
- z_api_attachment_test.c
- z_int_queryable_attachment_test.c
- z_int_pub_sub_attachment_test.c
---
Failed …

Attachment support implementation

---

Cargo.toml
examples/z_queryable_with_channels.c
include/zenoh_commons.h
include/zenoh_macros.h
src/closures/mod.rs
src/closures/query_channel.rs
src/closures/query_closure.rs
src/closures/response_channel.rs
src/queryable.rs

Since owned queries now exist, channels to allow moving them around would be useful.

introduce query channels

---

examples/CMakeLists.txt
examples/z_sub_thr.c

Throughput test had the same issue of using system time instead of wall time as #184.
This PR switch this to wall time using `CLOCK_MONOTONIC`.

Use wall time in throughput test

---

examples/z_get.c
examples/z_pub_attachment.c
examples/z_put.c
examples/z_sub_attachment.c
include/zenoh_commons.h
src/collections.rs
tests/z_api_attachment_test.c
tests/z_int_pub_sub_attachment_test.c
tests/z_int_queryable_attachment_test.c

This includes a breaking change that was approved by @Mallets, exposing more senseful constructors for `z_bytes_t`.

z_bytes: expose wrap and rename new to from_str

---

install/PackageConfig.cmake.in

Cmake install shouldn't hardcode install path.

Fix: cmake install shouldn't hardcode install path

---

Cargo.lock
Cargo.toml
Cargo.toml.in
include/zenoh_commons.h
src/commons.rs
src/info.rs

Closes https://github.com/eclipse-zenoh/zenoh/issues/668

adding `complete` option to publication_cache

---

include/zenoh_commons.h
src/platform/mod.rs
src/platform/random.rs

Add support for random-generating primitives (addresses #247)

Add support for random-generating primitives

---

docs/api.rst
include/zenoh_commons.h
src/keyexpr.rs
tests/z_api_keyexpr_test.c

add z_(owned_)keyexpr_t autocanonize initializers. Closes #267.

add z_(owned_)keyexpr_t autocanonize initializers

---

include/zenoh_commons.h
src/keyexpr.rs
tests/z_api_keyexpr_test.c

add z_keyexpr_relation_to api. Closes #269.

add z_keyexpr_relation_to api

---

docs/api.rst
include/zenoh_commons.h
src/attachment.rs
tests/z_api_attachment_test.c

add len() and is_empty() methods to z_attachment and z_owned_bytes_map_t. Closes #268.

add len() and is_empty() methods to z_attachment and z_owned_bytes_map_t

---

docs/api.rst
include/zenoh_commons.h
src/liveliness.rs

Rename zc_owned_liveliness_get_options_t to zc_liveliness_get_options_t

---

src/attachment.rs
src/commons.rs
src/config.rs
src/get.rs
src/keyexpr.rs
src/lib.rs
src/platform/synchronization.rs
src/publication_cache.rs
src/publisher.rs
src/pull_subscriber.rs
src/queryable.rs
src/querying_subscriber.rs
src/session.rs
src/subscriber.rs

make impl_guarded_transmute automatically implement From, Deref and DerefMut.
Part of #251 PR.

implementation_guarded_transmute with from and deref

---

.cargo/config.toml

[This is needed to build the `cdylib` crate type for `-musl` targets.](https://github.com/rust-lang/rust/issues/59302)

feat: Statically link C runtime on `-musl` targets

---

.github/workflows/release.yml
CMakeLists.txt
Cargo.lock
Cargo.toml
Cargo.toml.in
build.rs

fix: Release workflow

---

ci/scripts/bump-and-tag.bash

While `git push` pushes the current branch into its remote, `git push <tag>` doesn't push the tag.

fix: Specify git remote when pushing the tag

---

examples/parse_args.h
examples/z_delete.c
examples/z_get.c
examples/z_get_liveliness.c
examples/z_info.c
examples/z_liveliness.c
examples/z_non_blocking_get.c
examples/z_ping.c
examples/z_pong.c
examples/z_pub.c
examples/z_pub_attachment.c
examples/z_pub_cache.c
examples/z_pub_shm.c
examples/z_pub_thr.c
examples/z_pull.c
examples/z_put.c
examples/z_query_sub.c
examples/z_queryable.c
examples/z_queryable_with_channels.c
examples/z_sub.c
examples/z_sub_attachment.c
examples/z_sub_liveliness.c
examples/z_sub_thr.c

These changes remove reading from stdin for all examples, and align their behaviors and outputs across projects.
This PR is part of an effort across currently active Zenoh projects. To maintain examples' implementations as close to each other as possible, any changes identified in other projects will be replicated in this PR. As such, **please do not merge these changes until all PRs are ready for merging**.
Related PRs:
- https://github.com/eclipse-zenoh/zenoh/pull/768
- https://github.com/eclipse-zenoh/zenoh-cpp/pull/103
- https://github.com/eclipse-zenoh/zenoh-java/pull/45
- https://github.com/eclipse-zenoh/zenoh-kotlin/pull/47
- https://github.com/eclipse-zenoh/zenoh-pico/pull/359
- https://github.com/eclipse-zenoh/zenoh-python/pull/150

Align examples and remove reading from stdin

---

install/CMakeLists.txt

This is the default build type for debhelper (Debian).

Fix build with CMAKE_BUILD_TYPE=None

---

include/zenoh.h

fix header include order to include stddef.h before zenoh_opaque.h

fix header include order

---

docs/api.rst
docs/examples.rst
examples/z_get.c
examples/z_get_liveliness.c
examples/z_non_blocking_get.c
examples/z_query_sub.c
examples/z_queryable.c
examples/z_queryable_with_channels.c
examples/z_sub.c
examples/z_sub_attachment.c
examples/z_sub_liveliness.c
include/zenoh_commons.h
src/keyexpr.rs
tests/z_api_alignment_test.c
tests/z_api_keyexpr_drop_test.c
tests/z_api_keyexpr_test.c
tests/z_int_pub_cache_query_sub_test.c
tests/z_int_pub_sub_attachment_test.c
tests/z_int_pub_sub_test.c

undo pr #413; 
rename z_keyexpr_to_string into z_keyexpr_as_view_string;

rename z_keyexpr_to_string into z_keyexpr_as_view_string

---

include/zenoh_commons.h
src/commons.rs
src/publisher.rs
src/put.rs
tests/z_int_pub_sub_test.c

Add:
- `timestamp` to the: `z_delete_options_t`, `z_publisher_delete_options_t`, `z_publisher_put_options_t`, `z_put_options_t`
- `allowed_destination` to the: `z_publisher_options_t`, `z_delete_options_t`, `z_put_options_t` 
- `z_timestamp_new` method to create timestamp
Closes: https://github.com/eclipse-zenoh/zenoh-c/issues/384
NB: `congestion_control` already present for put, but for publisher it should be added as `z_publisher_set_congestion_control`, it will be done in separate PR

Add timestamp and allowed_destination properties

---

include/zenoh_commons.h
src/publisher.rs

- `z_publisher_set_congestion_control`
- `z_publisher_set_priority`
- `z_publisher_set_allowed_destination`

Add z_publisher_set_* methods

---

include/zenoh_commons.h
src/queryable.rs
tests/z_int_queryable_test.c

- congestion_control
- priority
- is_express
- timestamp
Closes: https://github.com/eclipse-zenoh/zenoh-c/issues/389

Add missing properties to z_query_reply_options_t

---

.github/workflows/ci.yml
examples/z_liveliness.c
examples/z_non_blocking_get.c
examples/z_ping.c
examples/z_pub_attachment.c
examples/z_pub_cache.c
examples/z_pull.c
examples/z_put.c
examples/z_query_sub.c
examples/z_queryable.c
examples/z_queryable_with_channels.c
examples/z_scout.c
examples/z_sub.c
examples/z_sub_attachment.c
examples/z_sub_liveliness.c
examples/z_sub_thr.c
include/zenoh_commons.h
include/zenoh_memory.h
tests/z_api_alignment_test.c
tests/z_api_config_test.c
tests/z_api_drop_options.c
tests/z_api_keyexpr_drop_test.c
tests/z_api_liveliness.c
tests/z_api_null_drop_test.c
tests/z_api_payload_test.c
tests/z_int_helpers.h
tests/z_int_pub_cache_query_sub_test.c
tests/z_int_pub_sub_attachment_test.c
tests/z_int_queryable_attachment_test.c

Enforce clang formatting to be sure that all *.c and *.h files correctly formatted

Enforce clang formatting

---

build-resources/opaque-types/src/lib.rs
examples/z_queryable.c
examples/z_queryable_with_channels.c
include/zenoh_commons.h
include/zenoh_macros.h
splitguide.yaml
src/commons.rs
src/get.rs
src/queryable.rs
tests/z_api_alignment_test.c
tests/z_int_queryable_attachment_test.c
tests/z_int_queryable_test.c

And replace it by:
- `z_query_payload`
- `z_query_encoding`
- `z_reply_err_payload`
- `z_reply_err_encoding`
Closes: https://github.com/eclipse-zenoh/zenoh-c/issues/390

Remove z_query_value

---

.github/workflows/ci.yml
build.rs
include/zenoh_commons.h
include/zenoh_concrete.h

Not all platform have clang-format preinstalled, and cbindgen can't apply required formatting, therefore we will exclude checking auto-generated files

Exclude auto-generated files from clang-format

---

include/zenoh_commons.h
include/zenoh_macros.h
src/publisher.rs

It is required for `z_publisher_set_priority`, `z_publisher_set_congestion_control`, etc

Add z_publisher_loan_mut

---

include/zenoh_commons.h
src/get.rs
src/publisher.rs

- `accept_replies`
- `allowed_destination`
- `congestion_control`
- `priority`
Closes: https://github.com/eclipse-zenoh/zenoh-c/issues/387

Add missing properties to z_get_options_t

---

src/payload.rs

cargo fmt fix for PR #463

---

CMakeLists.txt
README.md

We will be releasing `alpha/beta/rc` versions in eclipse-zenoh/zenoh. Those versions cannot all be mapped into the CMake version tweak. This pull request suggests using the umbrella suffix `pre` to means any of `alpha/beta/rc` so we can still have a one-to-one map between CMake versions and SemVer versions.

Replace `-rc` with `-pre` and document versioning

---

docs/api.rst
docs/examples.rst

fix string-related function names in docs

fix string-related function names in docs

---

examples/z_put.c
include/zenoh_commons.h
src/commons.rs
tests/z_int_pub_sub_attachment_test.c
tests/z_int_queryable_attachment_test.c

As titled. I think it was forgotten in #190.

fix: typos of attachment

---

include/zenoh_commons.h
src/publisher.rs

Add default encoding for publisher; 
Closes #487.

add default encoding for publisher

---

Cargo.lock
Cargo.toml
docs/api.rst
include/zenoh_commons.h
include/zenoh_macros.h
src/commons.rs
src/encoding.rs
src/lib.rs
src/put.rs
tests/z_api_encoding_test.c

add z_encoding_set_schema functions (corresponding to zenoh-rust Encoding::with_schema)
add predefined encoding constants;
add z_encoding_clone function;
Closes #365.

Encoding alignment with Zenoh-rust

---

docs/api.rst
include/zenoh_commons.h
src/config.rs

add zc_config_from_env function;
Closes #270.

add zc_config_from_env function

---

install/PackageConfig.cmake.in

As `find_package(zenohc)` can be called transitively by the `<pkg>-config.cmake` files of `<pkg>` that depends publicly on `zenohc`, it is important to ensure that `find_package(zenohc)` can be called two or more times. At the moment, if one calls two times `find_package(zenohc)` , the following error appears:
~~~
CMake Error at /Users/runner/Miniforge3/conda-bld/libzenohc_1719163375604/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/cmake/zenohc/zenohcConfig.cmake:50 (add_library):
add_library cannot create imported target "__zenohc_static" because another
target with the same name already exists.
Call Stack (most recent call first): …

Ensure that find_package(zenohc) can be called two times

---

tests/CMakeLists.txt

The test use functions such as `sem_wait` (https://man7.org/linux/man-pages/man3/sem_wait.3.html) that on Linux are contained in the `pthread` library. The classical way of linking to `pthread` in CMake is to use the `Threads::Threads` target, see https://cmake.org/cmake/help/v3.30/module/FindThreads.html .

Link tests to Threads::Threads

---

CMakeLists.txt
Cargo.toml
Cargo.toml.in
build-resources/opaque-types/Cargo.toml
build-resources/opaque-types/src/lib.rs
examples/CMakeLists.txt
include/zenoh_commons.h
splitguide.yaml
src/commons.rs
src/get.rs
src/keyexpr.rs
src/lib.rs
src/publisher.rs
src/put.rs
src/queryable.rs
src/querying_subscriber.rs
tests/CMakeLists.txt
tests/z_api_keyexpr_test.c
tests/z_int_pub_sub_test.c
tests/z_int_queryable_test.c

move SourceInfo, liveliness, KeyExpr::relation_to and zenoh-ext functionality under UNSTABLE feature

move SourceInfo, liveliness, KeyExpr::relation_to and zenoh-ext functionality under UNSTABLE feature

---

.readthedocs.yaml

Some auto generated files (e.g. include/zenoh_opaque.h) are platform specific so they are git ignored. They contain documentation that should be published as well, so this step makes sure all the files are in the checkout before publishing them to readthedocs.io

Cargo build before docs generation

---

install/PackageConfig.cmake.in

remove redundant compile definitions for feature options since they are already available through the zenoh_configure.h

remove redundant compile definitions for feature options

---

docs/api.rst
include/zenoh_commons.h
src/collections.rs

Methods `z_slice_wrap`, `z_slice_from_str` are legacy and we don't need them 
Closes: https://github.com/eclipse-zenoh/zenoh-c/issues/475

Remove legacy slice methods

---

examples/z_queryable.c
examples/z_queryable_shm.c
examples/z_queryable_with_channels.c
include/zenoh_commons.h
src/queryable.rs

fix queryable examples to account for missing payload

fix queryable examples to account for an empty payload

---

src/shm/client_storage/mod.rs

the `Arc` is now under `ReadGuard`

build fix after cargo.lock update

---

Cargo.lock
Cargo.toml
Cargo.toml.in
src/publication_cache.rs
src/querying_subscriber.rs
src/shm/client_storage/mod.rs

Depends on https://github.com/eclipse-zenoh/zenoh/pull/1286.

Rename `close` to `undeclare` for Publication Cache and Querying Subscriber

---

build-resources/opaque-types/Cargo.toml
build-resources/opaque-types/src/lib.rs
build.rs

by default do not generate panic messages in opaque-types subprobject for making easier to check if it compiles or not

generate panic messages only if explicitly asked

---

docs/examples.rst
examples/z_get.c
examples/z_get_liveliness.c
examples/z_get_shm.c
examples/z_non_blocking_get.c
examples/z_pub_cache.c
examples/z_pull.c
examples/z_queryable_with_channels.c
include/zenoh_commons.h
include/zenoh_concrete.h
include/zenoh_macros.h
src/closures/query_channel.rs
src/closures/response_channel.rs
src/closures/sample_channel.rs
src/result.rs
tests/z_api_liveliness.c
tests/z_api_payload_test.c
tests/z_api_shm_test.c
tests/z_int_pub_cache_query_sub_test.c
tests/z_int_pub_sub_test.c
tests/z_int_queryable_attachment_test.c
tests/z_int_queryable_test.c

make z_recv/z_try_recv return z_result_t to allow differentiating between different cases without the need to call z_check on constructed object.
Closes #568.

z_recv/z_try_recv without the need of z_check

---

Cargo.lock
build-resources/opaque-types/src/lib.rs
docs/api.rst
include/zenoh_commons.h
include/zenoh_macros.h
splitguide.yaml
src/payload.rs
tests/z_api_payload_test.c

made z_bytes_writer non-owned;
added z_bytes_writer_append(...) and z_bytes_writer append_bounded(...) (aka writer.serialize()); 
added z_bytes_reader_read_bounded(...);

z_bytes_reader and z_bytes_writer update

---

build-resources/opaque-types/src/lib.rs
docs/api.rst
examples/z_pub.c
examples/z_pub_shm.c
include/zenoh_commons.h
src/publisher.rs

rename zc_publisher_matching_listener_callback -> zc_publisher_matching_listener_declare; Closes #367.
added zc_publisher_get_matching_status; Closes #386.

zc_publisher_matching_listener update

---

examples/z_get_shm.c
examples/z_pub_shm.c
examples/z_queryable_shm.c

fix: use `z_move` in shm examples

---

examples/z_info.c

This PR has partially fixed #601. The remaining task is aligning the ZID order with the Rust side. Despite the same underlying`[u8; 16]`, we display the ZID in LSB order in Rust. That's why we saw a mismatch (actually they are the reverse of each other). 
1. Modify the example z_info (and any other usages) to print ZID reversely.
2. Provide a `zid_to_string` function to avoid any confusion.
3. Change LSB order formatting in [the uhlc crate](https://github.com/atolab/uhlc-rs).

fix: misuse the callback in z_info

---

.github/workflows/ci.yml
Cargo.lock
src/transmute.rs

Fix for build outside of source directory like this:
```bash
md foo
cmake -S zenoh-c -B foo
cmake --build foo
```
The error comes from crate "time 0.3.28", this is known issue resolved in further versions:
https://users.rust-lang.org/t/time-crate-compilation-error/111789/5
```
error[E0282]: type annotations needed for `Box<_>`
--> /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/time-0.3.28/src/format_description/parse/mod.rs:83:9
|
83 |     let items = format_items
|         ^^^^^
...
86 |     Ok(items.into())
|              ---- type must be known at this point
|
help: consider giving `items` an explicit type, where the placeholders `_` are specified
|
83 |     let items: Box<_> = format_items
|              ++++++++
```

build in separate directory failure fix

---

CMakeLists.txt

When building using cargo's --manifest-path option the toolchain configuration file within the manifest directory is ignored. Ensuring a copy of the rust-toolchain.toml file is in the build directory ensures the toolchain settings are picked up when building via cmake.

Ensure build directory contains a copy of rust-toolchain.toml

---

include/zenoh_commons.h
src/get.rs
src/querying_subscriber.rs

We need this fix to resolve the issue in rmw_zenoh_cpp. 
- https://github.com/ros2/rmw_zenoh/issues/263
- https://github.com/ros2/rmw_zenoh/pull/269

fix: add `accept_replies` to `z_get_options_t` and use it in `ze_querying_subscriber_get`

---

src/querying_subscriber.rs

fix: properly apply `z_get_options_t` in `ze_querying_subscriber_get`

---

README.md
install/CMakeLists.txt

use same name for debug and release packages

use same name for debug and release packages

---

.github/workflows/ci.yml
CMakeLists.txt
README.md
install/CMakeLists.txt
install/PackageConfig.cmake.in
tests/CMakeLists.txt

- replace ZENOHC_LIB_STATIC with more common BUILD_SHARED_LIBS
- only install either shared or static libraries depending on BUILD_SHARED_LIBS
- do not build shared/static build test depending on BUILD_SHARED_LIBS
- rearrange cmake lines to make clearer to which type of lib they refer

cmake clean up

---

include/zenoh_commons.h
src/publication_cache.rs
src/publisher.rs
src/queryable.rs
src/querying_subscriber.rs
src/subscriber.rs

make z_drop on zenoh entities call actual drop instead of undeclare.
This is in particular will be required to support https://github.com/eclipse-zenoh/zenoh/pull/1334.

make z_drop on zenoh entities call actual drop instead of undeclare

---

docs/api.rst
include/zenoh_commons.h
src/publication_cache.rs
src/queryable.rs

add ze_publication_cache_keyexpr();
add z_queryable_id();
add allowed origin to z_queryable_options_t;
Closes #392 
Closes #373

add missing zenoh-rust functionality

---

include/zenoh_commons.h
include/zenoh_macros.h

followup update: the headers were not updated in 
https://github.com/eclipse-zenoh/zenoh-c/pull/603 and https://github.com/eclipse-zenoh/zenoh-c/commit/d6eecefd664f21fb28dd86afe9f48ee5b56458a7

updated autogenerared headers

---

build-resources/opaque-types/src/lib.rs
docs/api.rst
include/zenoh_commons.h
src/get.rs
src/keyexpr.rs
src/session.rs

remove z_session_clone
add z_keyexpr_clone
add z_reply_err_clone
Closes #644

Align _clone functions

---

docs/api.rst
include/zenoh_commons.h
src/config.rs
tests/z_api_config_test.c

remove z_config_client and z_config_peer

remove z_config_client and z_config_peer

---

build.rs
include/zenoh_macros.h

Add z_clone macro

---

Cargo.lock
build-resources/opaque-types/Cargo.lock
build-resources/opaque-types/src/lib.rs
include/zenoh_commons.h
src/config.rs
src/info.rs
src/keyexpr.rs
src/liveliness.rs
src/publication_cache.rs
src/publisher.rs
src/queryable.rs
src/querying_subscriber.rs
src/session.rs
src/shm/provider/alloc_layout_impl.rs
src/shm/provider/shm_provider_impl.rs
src/subscriber.rs

align with new dev/arcsession changes
Notably dropping subscriber/queryable/fetching_subscriber no longer drops their callbacks (this is achieved through undeclare functions).
Closing / dropping session (given that it is no longer clone able) drops all non-undeclared callbacks.

align with new dev/arcsession changes

---

build-resources/opaque-types/src/lib.rs
docs/api.rst
include/zenoh_commons.h
include/zenoh_macros.h
src/collections.rs
src/scouting.rs

add hello and string_array clones
move owned_string_array outside of option

add hello and string_array clones

---

src/closures/query_channel.rs
src/closures/response_channel.rs
src/closures/sample_channel.rs
src/get.rs
src/liveliness.rs
src/queryable.rs
src/querying_subscriber.rs
src/scouting.rs
src/subscriber.rs

wrap loaned objects inside callbacks into option to pretend they are owned

wrap loaned objects inside callbacks into option to pretend they are owned

---

include/zenoh_commons.h
src/payload.rs

update docs regarding undefined behavior when using multiple z_bytes_writers

update docs regarding undefined behavior when using multiple z_bytes_writers

---

build.rs
docs/api.rst
include/zenoh_commons.h
include/zenoh_macros.h
src/closures/hello_closure.rs
src/closures/log_closure.rs
src/closures/matching_status_closure.rs
src/closures/query_closure.rs
src/closures/reply_closure.rs
src/closures/sample_closure.rs
src/closures/zenohid_closure.rs

add explicit closure constructors;
Closes #691

add explicit closure constructors

---

docs/concepts.rst
docs/index.rst

closes
https://github.com/eclipse-zenoh/zenoh-c/issues/651
https://github.com/eclipse-zenoh/zenoh-c/issues/490

Documnetation page about zenoh-c types concepts

---

include/zenoh_commons.h
src/platform/sleep.rs

Sister PR: https://github.com/eclipse-zenoh/zenoh-pico/pull/681

Change `z_sleep_*` result type to z_result_t

---

Cargo.toml
build.rs
cbindgen.toml
docs/Doxyfile
examples/z_pub.c
examples/z_pub_shm.c
examples/z_scout.c
examples/z_sub.c
examples/z_sub_shm.c
examples/z_sub_thr.c
include/zenoh_commons.h
tests/z_api_alignment_test.c
tests/z_api_keyexpr_test.c
tests/z_api_null_drop_test.c
tests/z_int_pub_sub_test.c
tests/z_int_queryable_test.c

add Z_FEATURE prefix to feature macros to avoid name collision

add Z_FEATURE prefix to feature macros to avoid name collision

---

examples/z_pub_thr.c

fix pub_thr to generate similar payload to rust to avoid difference in throughput

fix pub_thr example to generate similar payload to rust to avoid difference in throughput

---

examples/z_bytes.c

add z_bytes example
Closes #687

add z_bytes example

---

.github/workflows/ci.yml
CMakeLists.txt
Cargo.lock
Cargo.toml
Cargo.toml.in
README.md
build-resources/opaque-types/Cargo.lock
build-resources/opaque-types/Cargo.toml
build.rs
include/zenoh_commons.h
include/zenoh_macros.h

Support for zenoh features
Closes #626

Support for zenoh features

---

Cargo.lock
build-resources/opaque-types/Cargo.lock
include/zenoh_concrete.h
src/get.rs
src/publisher.rs
src/put.rs
src/result.rs

feat: add an error code for SessionClosedError

---

Cargo.lock
Cargo.toml
Cargo.toml.in

update zenoh-c after varint made internal in https://github.com/eclipse-zenoh/zenoh/pull/1498

import zenoh ext with internal feature for using VarInt

---

include/zenoh_commons.h
src/collections.rs
src/keyexpr.rs
src/liveliness.rs
src/publisher.rs
src/queryable.rs
src/scouting.rs
src/serialization.rs
src/shm/buffer/zshmmut.rs
src/subscriber.rs

Align doxygen parameters with real parameters to generate proper documentation and avoid doxygen warnings

Fix doxygen warnings

---

build.rs
include/zenoh_macros.h

add closure typedefs for C.
Closes #762.

add closure typedefs for C

---

CMakeLists.txt
build.rs
include/zenoh.h
include/zenoh_commons.h
include/zenoh_macros.h

fixes https://github.com/eclipse-zenoh/zenoh-c/issues/354

auto generate zenoh version in header from version.txt

---

.github/workflows/release.yml
ci/scripts/bump-and-tag.bash

Aligning with [ci repository](https://github.com/eclipse-zenoh/ci/pull/239/files) to not tag the repo when we are running release dry-run

fix: Don't tag release branch during dry-run

---

examples/z_queryable_shm.c
examples/z_sub_shm.c
include/zenoh_commons.h
src/zbytes.rs

rename `to_loaned_shm` -> `as_loaned_shm`  to prevent any possible misleading
[closes #809]

to_loaned_shm -> as_loaned_shm 

---

build-resources/opaque-types/src/lib.rs
docs/api.rst
examples/z_get_liveliness.c
examples/z_liveliness.c
examples/z_sub_liveliness.c
include/zenoh_commons.h
include/zenoh_macros.h
splitguide.yaml
src/liveliness.rs
tests/z_api_liveliness.c

- zc_ prefix replaced to z_
- declaration_options renamed to token_options

renamed z_liveliness* function to give them correct names

---

examples/z_bytes.c
examples/z_pub.c

Users take the examples as a reference and learn how to construct a `z_owned_bytes` properly. After browsing the example codes, I propose removing unnecessary `copy` in some cases while retaining a few for scenario comparisons.

refactor: remove unnecessary copy in examples

---

build-resources/opaque-types/src/lib.rs

technical library opaque-types for builder.rs should work with deprecated API

Add deprecation allowance for builder.rs

---

examples/parse_args.h
examples/z_liveliness.c

add --cfg arg support

---

examples/parse_args.h
examples/z_pub_thr.c

fix priority parsing in z_pub_thr example

fix priority parsing

---

examples/z_advanced_pub.c
examples/z_advanced_sub.c
include/zenoh_commons.h
src/advanced_publisher.rs
src/advanced_subscriber.rs
tests/z_int_advanced_pub_sub_test.c

refactor advanced publisher/subscriber options: now suboptions are placed inside the enclosing structure. Previous approach when main options structure contained references to suboptions restricts the API extensibility: it was impossible to set subsoptions by functions which accepts only reference to main options structure.

advanced publisher/subscriber options contains cache options inside

---

.github/workflows/ci.yml
.markdownlint.yaml
README.md
docs/README.md

As https://github.com/eclipse-zenoh/zenoh/issues/1666, fix the README.md format and update CI.

Add CI for checking markdown format.

---

docs/api.rst
include/zenoh_commons.h
src/zbytes.rs
tests/z_api_payload_test.c

add z_bytes_get_contiguous_view function;

add possibility to get contiguous view of z_bytes data when it is not fragmented

---

docs/api.rst
include/zenoh_commons.h
src/advanced_subscriber.rs
src/subscriber.rs

add ze_advanced_subscriber_keyexpr;
add ze_advanced_subscriber_id;
add z_subscriber_id;
closes #869

add missing subscriber methods

---

include/zenoh_commons.h
src/liveliness.rs

In zenoh rust we have u64 timeout and other timeouts in zenoh-c also exposed as u64
Related PRs:
https://github.com/eclipse-zenoh/zenoh-cpp/pull/354
https://github.com/eclipse-zenoh/zenoh-pico/pull/845

Fix liveliness timeout type

---

docs/api.rst
examples/z_advanced_sub.c
include/zenoh_commons.h
src/advanced_publisher.rs
src/advanced_subscriber.rs
tests/z_int_advanced_pub_sub_test.c

support for default recovery option without last sample miss detection (i.e. without heartbeat nor periodic queries from subscriber's side)

support for advanced pubs default recovery option without last sample miss detection

---

docs/api.rst
include/zenoh_commons.h
src/liveliness.rs

Rename zc_liveliness_declare_background_subscriber to z_liveliness_declare_background_subscriber and mark it as stable

Rename zc_liveliness_declare_background_subscriber and make it stable

---

build-resources/opaque-types/src/lib.rs
docs/api.rst
examples/z_pub.c
examples/z_pub_shm.c
examples/z_querier.c
include/zenoh_commons.h
include/zenoh_macros.h
splitguide.yaml
src/advanced_publisher.rs
src/closures/matching_status_closure.rs
src/matching.rs
src/publisher.rs
src/querier.rs

Rename matching methods and types from `zc_*` to `z_*` because it was already implemented in Zenoh Pico

Rename matching methods and types from `zc_*` to `z_*`

---

.github/workflows/ci.yml
Cargo.lock
Cargo.toml
Cargo.toml.in
build-resources/opaque-types/Cargo.lock
build.rs
include/zenoh_commons.h
src/closures/hello_closure.rs
src/closures/log_closure.rs
src/closures/matching_status_closure.rs
src/closures/miss_closure.rs
src/closures/query_closure.rs
src/closures/reply_closure.rs
src/closures/sample_closure.rs
src/closures/zenohid_closure.rs
src/config.rs
src/encoding.rs
src/keyexpr.rs
src/queryable.rs
src/querying_subscriber.rs
src/scouting.rs
src/session.rs
src/shm/buffer/zshm.rs
src/shm/cleanup.rs

Fix clippy warnings.
What is left out: 
```
$ cargo +stable clippy --all-features --all-targets --fix --lib -p zenoh-c --allow-dirty
Compiling zenoh-c v1.2.1 (/Users/luca/Repository/eclipse-zenoh-c)
warning: manually constructing a nul-terminated string
--> src/config.rs:33:53
|
33 | pub static Z_CONFIG_MODE_KEY: &c_char = unsafe { &*(b"mode\0".as_ptr() as *const c_char) };
|                                                     ^^^^^^^^^ help: use a `c""` literal: `c"mode"`
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#manual_c_str_literals
= note: `#[warn(clippy::manual_c_str_literals)]` on by default
warning: manually constructing a nul-terminated string
--> src/config.rs:36:17
|
36 |     unsafe { &*(b"connect/endpoints\0".as_ptr() as …
```

Fix clippy warnings

---

.github/workflows/ci.yml

This way in the Github web ui it's clearer which job in the matrix is running which tests.

chore: better name for workflow step

---

.github/workflows/ci.yml

With the toolchain bump proposed in https://github.com/eclipse-zenoh/zenoh-c/pull/933, we need to guarantee zenoh-c can still be built on rust 1.75

fix: add ci check for rust 1.75

---

CMakeLists.txt

As the cargo build take long time when Ninja backend is used we have no informations on the build progress. It might be usefull for CI purpose and make smooth piping and parsing (as in Yocto integration).

cmake: add USES_TERMINAL in custom command

---

CMakeLists.txt

Because in CMake build configs are case-insensitive! The build failed with `-DCMAKE_BUILD_TYPE=debug`

Make build config case-insensitive as it should be

---

Cargo.toml
Cargo.toml.in
src/lib.rs

Fixes #294 
Adds entrypoint `alternative_rusty_entry_point()` and installs SIGPIPE to be ignored there
Tested manually with static and shared library

Rust entrypoint

---

include/zenoh_commons.h
include/zenoh_constants.h
src/config.rs

replace extern const strings with macro defines since these constants are not correctly exported on windows
Resolves https://github.com/eclipse-zenoh/zenoh-cpp/issues/468

replace extern const strings with macro defines

---

CMakeLists.txt

There're couple unnecessary trailing spaces in CMakeLists.txt file. Remove them to make cmake formatter happy

styles: remove the trailing spaces in cmake file

---

CMakeLists.txt
build.rs
install/PackageConfig.cmake.in

**after**
```lang=shell
$ readelf -d ../target/release/libzenohc.so | grep SONAME
0x000000000000000e (SONAME)             Library soname: [libzenohc.so]
```
**before**
```lang=shell
$ readelf -d ../target/release/libzenohc.so | grep SONAME
[empty return]
```

Add SONAME on linux cdylib

---

ci/scripts/bump-and-tag.bash

Fix https://github.com/eclipse-zenoh/ci/issues/329.

fix: avoid updating Cargo.lock to version 4

---

examples/z_ping.c
examples/z_ping_shm.c
examples/z_pong.c
examples/z_pub.c
examples/z_pub_shm.c
examples/z_querier.c

Handle the return codes in the following cases (at least):
- open session
- declare publisher
- declare subscriber
Other API calls should be handled as well later.

examples: don't ignore return status code

---

src/platform/synchronization.rs

When building with `panic="abort"` and `std` built from source, the size of `Mutex<()>` varies when wrapped in `Option<>` or not such that the owned and loaned types have different sizes.
This is specifically due to the [`poison` flag field in `Mutex`](https://github.com/rust-lang/rust/blob/28f1c807911c63f08d98e7b468cfcf15a441e34b/library/std/src/sync/poison/mutex.rs#L177) getting [compiled out when the `panic` mode is not set to `"unwind"`](https://github.com/rust-lang/rust/blob/master/library/std/src/sync/poison.rs#L89-L92). This field's omission pushes the size of the struct to the edge of the 16 byte boundary such that niche optimization no longer has bits to fiddle with after aligning to 8 bytes.
The build fails as follows:
```
note: evaluation panicked: Size mismatch: type …
```

Fix build with panic="abort"

---

CMakeLists.txt

When using `zenohc` via cmake's `FetchContent` mechanism,
I get the following warnings:
```
CMake Warning (dev) in build/_deps/zenohc-src/CMakeLists.txt:
Policy CMP0111 is not set: An imported target missing its location property
fails during generation.  Run "cmake --help-policy CMP0111" for policy
details.  Use the cmake_policy command to set the policy and suppress this
warning.
IMPORTED_LOCATION or IMPORTED_IMPLIB not set for imported target
"zenohc_shared".
```
and on linking,
```
ninja: error: 'zenohc_shared-NOTFOUND', needed by 'myexecutable', missing and no known rule to make it
```
Apparently, the `IMPORTED_LOCATION` is really needed ;)
This change sets the correct library and makes the linking work fine for me.
Please note: While a generator expression would be nicer, we sadly …

CMP0111 requires IMPORTED_LOCATION or IMPORTED_IMPLIB being set

---

.github/workflows/release.yml

More specifically the windows-2019 got deprecated which causes the release workflow to be cancelled.

ci: update release workflow to use latest runners

---

examples/z_advanced_pub.c
examples/z_pub.c
examples/z_querier.c

The following syntax is fine in C++ but causes MSVC Error C2059 (syntax error) in C.
The standard way is to initialize it with `{0}`.
```c
char buf[256] = {};
```
```txt
Microsoft (R) Build Engine version 16.11.2+f32259642 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.
C:\dev\zenoh-c\examples\z_pub.c(72,22): error C2059: syntax error: '}' [C:\dev\zenoh-c\build\examples\z_pub.vcxproj]
C:\dev\zenoh-c\examples\z_querier.c(91,22): error C2059: syntax error: '}' [C:\dev\zenoh-c\build\examples\z_querier.vcxproj]
```

fix: MSVC Error C2059

---

buildrs/opaque_types_generator.rs

When opaque-types project failed due to cargo issues, diagnostic was not handled. This caused cryptic errors on further stages of build instead

check for cargo error when generating opaque types
