eclipse-zenoh/zenoh-c

- CMakeLists.txt
- Makefile
Ref: eclipse-zenoh/zenoh-java#2
Signed-off-by: Julien Enoch <julien.enoch@adlinktech.com>
> Update build files to be used by zenoh-java build.

- Cargo.toml
- src/net/mod.rs
This merge leverages the new sync API for zenoh and provide some major performance improvements when using the C-binding for zenoh.
> Issue (#21)

- Cargo.toml
- Makefile
- include/zenoh.h
Updated the makefile to show how to build examples both with dynamic linkage and static linkage
> Add support for static linkage

- include/zenoh_commons.h
- src/config.rs
- src/publisher.rs
Sister PR: https://github.com/eclipse-zenoh/zenoh/pull/320.
> Don't expose local_routing which is unstable

- include/zenoh.h
- include/zenoh_commons.h
- include/zenoh_concrete.h
- splitguide.yaml
- src/get.rs
- src/keyexpr.rs
- src/publisher.rs
This time, no more architecture detection shenanigans
> fix layouts AGAIN

- examples/z_info.c
Copy of PR #76.
All credits to @clibequilibrium !
> Fixed z_info.c PID order

- CMakeLists.txt
> make pck-config file installation optional

- CMakeLists.txt
This fixes issue https://github.com/eclipse-zenoh/zenoh-c/issues/86
> added explicit path to cargo.toml

- .github/workflows/ci.yml
- include/zenoh_commons.h
- include/zenoh_concrete.h
- src/collections.rs
- src/get.rs
new niches unlocked \o/
but these new niches made some of the stack layouts wrong
> fix layouts for Rust 1.65

- Cargo.lock
- examples/z_get.c
- src/session.rs
This PR remove manual override of query target value in `z_get` example.
> Default query target in z_get example

- Cargo.lock
- Cargo.toml
- Cargo.toml.in
- include/zenoh_concrete.h
- src/get.rs
> fix layout

- src/keyexpr.rs
> fix keyexpr canonize

- CMakeLists.txt
- README.md
I just add few changes to facilitate cross-compilation. This will not affect any of the default cmake parameters.
> addapting CMakeLists.txt for cross-compilation

- include/zenoh_commons.h
- src/keyexpr.rs
- tests/z_api_alignment_test.c
- tests/z_api_keyexpr_test.c
API update accoridngly to variant (1) proposed in this discussion https://github.com/eclipse-zenoh/zenoh-pico/issues/173
> return zero as true and -1 as error

- include/zenoh_commons.h
- src/get.rs
To be merged after https://github.com/eclipse-zenoh/zenoh/pull/469
> Stabilize query with_value

- examples/z_get.c
> Update z_get example with query value

- include/zenoh_commons.h
- src/get.rs
fix for  issue https://github.com/eclipse-zenoh/zenoh-c/issues/158
> timeout parameter added to z_get_options_t

- tests/CMakeLists.txt
- tests/z_int_helpers.h
- tests/z_int_helpers_test.c
- tests/z_int_pub_cache_query_sub_test.c
- tests/z_int_pub_sub_test.c
- integration test support
- integration test helpers
- helpers test
- pub/sub test
- pub_cache/sub_query test
> Add interation tests

- tests/z_api_attachment_test.c
- tests/z_int_helpers.h
- tests/z_int_queryable_attachment_test.c
- tests/z_int_queryable_test.c
This PR fixes some warnings in MacOS build
> Fix MacOS build warnings

- Cargo.toml
- Cargo.toml.in
See https://github.com/eclipse-zenoh/zenoh/pull/640.
> Fix Debian package for `0.10.1-rc`

- .github/workflows/ci.yml
- Cargo.toml
- Cargo.toml.in
See https://github.com/eclipse-zenoh/zenoh/pull/639 and https://github.com/eclipse-zenoh/zenoh/pull/640.
> Reduce status checks & fix Debian package

- include/zenoh_macros.h
Found a bug in my previous PR.  
Is there a way to test this?
> Fix matching status

- examples/z_scout.c
- include/zenoh_commons.h
- src/lib.rs
- src/platform/clock.rs
- src/scouting.rs
add z_whatami_to_str api. Closes #271.
> add z_whatami_to_str api

- CMakeLists.txt
> removed cargo channel parameter by default

- include/zenoh_commons.h
- src/get.rs
- src/publisher.rs
> fix sizes of zcu_owned_matching_listener_t and z_owned_reply_t for arm32

- include/zenoh_macros.h
> Bugfix: Unable to build z_queryable_with_channels.c

- README.md
The PR is to:
1. Fix the Markdown lint issue
2. Specify the Rust version for zenoh-c
> Update README and specify Rust version

- build.rs
- include/zenoh_macros.h
refactoring of c-macros-generation code in build.rs to reduce amount of copy/paste.
> refactoring of c-macros-generation code in build.rs

- build-resources/opaque-types/src/lib.rs
- examples/z_get.c
- examples/z_get_liveliness.c
- examples/z_non_blocking_get.c
- examples/z_query_sub.c
- examples/z_queryable.c
- examples/z_queryable_with_channels.c
- examples/z_scout.c
- examples/z_sub.c
- examples/z_sub_attachment.c
- examples/z_sub_liveliness.c
- include/zenoh_commons.h
- include/zenoh_macros.h
- src/collections.rs
- src/commons.rs
- src/config.rs
- src/keyexpr.rs
- src/payload.rs
- src/queryable.rs
- src/scouting.rs
- tests/z_api_alignment_test.c
- tests/z_api_config_test.c
- tests/z_api_keyexpr_drop_test.c
- tests/z_api_keyexpr_test.c
- tests/z_api_null_drop_test.c
- tests/z_int_pub_cache_query_sub_test.c
- tests/z_int_pub_sub_attachment_test.c
- tests/z_int_pub_sub_test.c
- tests/z_int_queryable_attachment_test.c
- tests/z_int_queryable_test.c
\+ `cargo fmt` applied
Closes https://github.com/eclipse-zenoh/zenoh-c/issues/398
> Use `string` instead of `str`

- docs/api.rst
- include/zenoh_commons.h
- src/payload.rs
- tests/z_api_payload_test.c
- Add support for serialization/deserialization of arithmetic types
- Add more tests for z_bytes
- Add z_bytes_empty function
> Support for serialization/deserialization of arithmetic types

- examples/z_get.c
- examples/z_get_liveliness.c
- examples/z_non_blocking_get.c
- examples/z_query_sub.c
- examples/z_queryable.c
- examples/z_queryable_with_channels.c
- examples/z_sub.c
- examples/z_sub_attachment.c
- examples/z_sub_liveliness.c
- include/zenoh_commons.h
- src/keyexpr.rs
- tests/z_api_alignment_test.c
- tests/z_api_keyexpr_drop_test.c
- tests/z_api_keyexpr_test.c
- tests/z_int_pub_cache_query_sub_test.c
- tests/z_int_pub_sub_attachment_test.c
- tests/z_int_pub_sub_test.c
Closes https://github.com/eclipse-zenoh/zenoh-c/issues/397
> Change z_keyexpr_to_string to z_view_string_from_keyexpr

- include/zenoh_commons.h
- src/commons.rs
Closes https://github.com/eclipse-zenoh/zenoh-c/issues/380
> Add z_priority_default

- .github/workflows/ci.yml
artifacts actions v3 are deprecated
> chore: Update artifacts action to v4

- src/get.rs
- src/publication_cache.rs
- src/publisher.rs
- src/put.rs
- src/queryable.rs
- src/querying_subscriber.rs
- tests/z_api_drop_options.c
fix not properly dropped option parameters;
add corresponding test;
> fix not properly dropped option parameters

- Cargo.lock
- Cargo.toml
- Cargo.toml.in
- build-resources/opaque-types/Cargo.lock
- build-resources/opaque-types/Cargo.toml
- build-resources/opaque-types/src/lib.rs
- build.rs
- docs/api.rst
- docs/examples.rst
- examples/z_get.c
- examples/z_get_liveliness.c
- examples/z_non_blocking_get.c
- examples/z_pull.c
- examples/z_queryable_with_channels.c
- include/zenoh_commons.h
- include/zenoh_macros.h
- splitguide.yaml
- src/closures/mod.rs
- src/closures/query_channel.rs
- src/closures/query_closure.rs
- src/closures/reply_closure.rs
- src/closures/response_channel.rs
- src/closures/sample_channel.rs
- src/closures/sample_closure.rs
- tests/z_api_null_drop_test.c
- tests/z_int_queryable_attachment_test.c
- tests/z_int_queryable_test.c
handlers are now used from zenoh-rust
added ring handlers
reintroduced pull.c example via ring handler
added z_recv and z_try_recv generic macros
> channels implementation proposal

- docs/api.rst
- examples/z_liveliness.c
- include/zenoh_commons.h
- include/zenoh_macros.h
- splitguide.yaml
- src/liveliness.rs
- tests/z_api_liveliness.c
rename zc_liveliness_declare_subscriber_options_t -> zc_liveliness_subscriber_options_t;
add zc_liveliness_token_loan function;
add tests for liveliness;
> liveliness clean up

- include/zenoh_commons.h
- src/queryable.rs
Add:
- z_query_reply_del 
- z_query_reply_del_options_t
- z_query_reply_del_options_default
Closes: https://github.com/eclipse-zenoh/zenoh-c/issues/391
> Add reply_del support

- include/zenoh_commons.h
- src/publisher.rs
Related to: https://github.com/eclipse-zenoh/zenoh/pull/1124
> Remove publisher set methods

- include/zenoh_commons.h
- src/get.rs
Closes: https://github.com/eclipse-zenoh/zenoh-c/issues/388
> Add z_reply_replier_id

- docs/api.rst
- include/zenoh_commons.h
- src/publisher.rs
- `z_publisher_id`
Closes: https://github.com/eclipse-zenoh/zenoh-c/issues/385
> Add publisher id getter

- CMakeLists.txt
Fix INTERFACE includes (was incorrect when Cargo is generating to custom directory)
> Fix INTERFACE includes

- Cargo.lock
- include/zenoh_commons.h
- include/zenoh_macros.h
- src/payload.rs
Align this repo with latest changes introduced by https://github.com/eclipse-zenoh/zenoh/pull/1174
> Align Zenoh

- docs/api.rst
- examples/z_scout.c
- include/zenoh_commons.h
- src/keyexpr.rs
- src/liveliness.rs
- src/payload.rs
- src/publication_cache.rs
- src/querying_subscriber.rs
- src/scouting.rs
rename z_whatami_to_str -> z_whatami_to_view_string;
fix docs;
> fix_what_am_i_to_str name

- docs/api.rst
- include/zenoh_commons.h
- include/zenoh_macros.h
- src/config.rs
- src/scouting.rs
- src/session.rs
api fixes for compatibility with zenoh-pico
> api fixes for compatibility with zenoh-pico

- Cargo.lock
- Cargo.toml
- Cargo.toml.in
- build.rs
no longer use cpp, awk and sed for cbindgen output processing
Closes #535.
> No longer use cpp, awk and sed for cbindgen output processing

- Cargo.lock
- Cargo.toml
- include/zenoh_commons.h
- include/zenoh_macros.h
- src/payload.rs
> Fix shm doc

- examples/z_queryable_shm.c
> typo fix (how did that compile????)

- examples/z_pub_shm.c
- examples/z_queryable_shm.c
- examples/z_sub_shm.c
> Align SHM examples

- examples/z_pub_attachment.c
- tests/z_int_pub_sub_attachment_test.c
- tests/z_int_queryable_attachment_test.c
simplify tests and examples with attachment
> simplify tests and examples with attachment

- src/config.rs
log error messages when failing to manipulate the config
> log error messages when failing to manipulate the config

- docs/api.rst
- include/zenoh_commons.h
- src/payload.rs
- tests/z_api_payload_test.c
z_byte_writer_write now has interface that intends that it can write not all
>  add z_byte_writer_write_all

- Cargo.lock
- build-resources/opaque-types/Cargo.lock
- examples/z_get_shm.c
- examples/z_ping_shm.c
- examples/z_pong.c
- examples/z_pub_shm.c
- examples/z_pub_shm_thr.c
- examples/z_queryable_shm.c
- examples/z_sub.c
- examples/z_sub_shm.c
- examples/z_sub_thr.c
sister PR to https://github.com/eclipse-zenoh/zenoh/pull/1312
> Shm default

- Cargo.lock
- include/zenoh_commons.h
- src/subscriber.rs
Reliability  option made unstable accordingly to https://github.com/eclipse-zenoh/zenoh/issues/1307
> made reliability option unstable

- Cargo.lock
- build-resources/opaque-types/Cargo.lock
- build-resources/opaque-types/src/lib.rs
- include/zenoh_commons.h
- src/collections.rs
- src/payload.rs
- tests/z_api_payload_test.c
add functionality to iterate over z_bytes slices.
See https://github.com/eclipse-zenoh/zenoh/pull/1354
Closes #649
> add functionality to iterate over z_bytes slices

- Cargo.lock
- src/get.rs
- src/put.rs
- src/queryable.rs
- src/querying_subscriber.rs
followup to https://github.com/eclipse-zenoh/zenoh/pull/1376
> removed internal traits

- docs/api.rst
- include/zenoh_commons.h
- include/zenoh_macros.h
- src/lib.rs
fix zc_init_log_from_callback  name and signature
> fix zc_init_log_from_callback  name and signature

- docs/api.rst
- examples/parse_args.h
- examples/z_get_shm.c
- examples/z_pub_cache.c
- examples/z_pub_shm_thr.c
- examples/z_queryable_shm.c
- examples/z_sub.c
- examples/z_sub_shm.c
- examples/z_sub_thr.c
- include/zenoh_commons.h
- src/config.rs
- tests/z_api_config_test.c
- tests/z_int_pub_cache_query_sub_test.c
Closes: https://github.com/eclipse-zenoh/zenoh-c/issues/693
> Rename zc_config_insert_json to zc_config_insert_json5

- docs/api.rst
- include/zenoh_commons.h
- src/encoding.rs
- tests/z_api_encoding_test.c
add z_encoding_equals function to compare 2 encodings for equality
> add z_encoding_equals

- docs/api.rst
- include/zenoh_commons.h
- src/encoding.rs
> fix encoding constant name

- Cargo.lock
- Cargo.toml
- Cargo.toml.in
- build-resources/opaque-types/Cargo.lock
- build-resources/opaque-types/Cargo.toml
- build-resources/opaque-types/src/lib.rs
- examples/z_bytes.c
- examples/z_pub_attachment.c
- examples/z_put.c
- examples/z_sub_attachment.c
- include/zenoh_commons.h
- include/zenoh_macros.h
- splitguide.yaml
- src/lib.rs
- src/serialization.rs
- tests/z_api_null_drop_test.c
- tests/z_api_payload_test.c
- tests/z_int_pub_sub_attachment_test.c
- tests/z_int_queryable_attachment_test.c
> make serialization stable

- build-resources/opaque-types/Cargo.lock
- build-resources/opaque-types/Cargo.toml
fix for https://github.com/eclipse-zenoh/zenoh-c/pull/732#issuecomment-2387905718
> added zenoh-ext/internal feature for opaque-types generator

- docs/api.rst
- include/zenoh_commons.h
- src/serialization.rs
serialization support for bool
> serialization support for bool

- Cargo.lock
- build-resources/opaque-types/Cargo.lock
- build-resources/opaque-types/src/lib.rs
- src/closures/query_channel.rs
- src/closures/response_channel.rs
- src/closures/sample_channel.rs
See https://github.com/eclipse-zenoh/zenoh/pull/1504.
> Sync lockfile with Zenoh `e9f3b37` from `2024-10-08`

- Cargo.lock
- build-resources/opaque-types/Cargo.lock
- docs/api.rst
- docs/examples.rst
- examples/z_queryable.c
- examples/z_queryable_shm.c
- examples/z_queryable_with_channels.c
- include/zenoh_commons.h
- src/publication_cache.rs
- src/queryable.rs
- tests/z_api_alignment_test.c
- tests/z_api_double_drop_test.c
- tests/z_int_queryable_attachment_test.c
- tests/z_int_queryable_test.c
- tests/z_leak_queryable_get_test.c
add ze_publication_cache_declare_background;
rename z_declare_queryable into z_queryable_declare;
> add ze_publication_cache_declare_background

- ci/scripts/bump-and-tag.bash
During release, opaque-types Cargo.toml and Cargo.lock should be updated to point to the release version/branch
> fix: Update opaque-types Cargo.toml during release

- build-resources/opaque-types/src/lib.rs
- include/zenoh_commons.h
- include/zenoh_macros.h
- src/closures/mod.rs
- src/closures/zenohid_closure.rs
- src/info.rs
- src/lib.rs
fix for https://github.com/eclipse-zenoh/zenoh-c/issues/705
> moved actually stable functionality from unstable feature

- build-resources/opaque-types/src/lib.rs
- src/closures/hello_closure.rs
- src/closures/mod.rs
- src/closures/query_closure.rs
- src/closures/reply_closure.rs
- src/closures/sample_closure.rs
- src/closures/zenohid_closure.rs
- src/info.rs
- src/lib.rs
https://github.com/eclipse-zenoh/zenoh-c/issues/714
> added missing z_xxx_loan_mut functions

- .github/workflows/ci.yml
- CMakeLists.txt
- examples/z_ping.c
fix z_ping example;
add option to treat compile warnings as errors;
> fix z_ping example

- README.md
readme update for cross-compilation
> readme update for cross-compilation

- Cargo.lock
- build-resources/opaque-types/Cargo.lock
> latest zenoh

- README.md
- build-resources/opaque-types/src/lib.rs
- docs/examples.rst
- examples/README.md
- examples/z_pub_thr.c
- examples/z_put.c
- examples/z_queryable.c
- examples/z_scout.c
- examples/z_storage.c
- examples/z_sub_thr.c
- include/zenoh_commons.h
- src/keyexpr.rs
- src/session.rs
clarify docs;
align examples with rust
> fix docs/align examples with rust

- include/zenoh_commons.h
- src/encoding.rs
add internal functions for (de)composing encoding to/from id and string
> add internal functions for (de)composing encoding to/from id and string

- Cargo.lock
- build-resources/opaque-types/Cargo.lock
- docs/api.rst
- examples/z_advanced_pub.c
- examples/z_advanced_sub.c
- include/zenoh_commons.h
- src/advanced_publisher.rs
- src/advanced_subscriber.rs
- tests/z_int_advanced_pub_sub_test.c
fix advanced pub/sub;
enable heartbeat support;
bump zenoh version;
> heartbeat support for advanced pub/sub

- .github/workflows/ci.yml
run apt-get update for Cross compile on ubuntu-latest
> run apt-get update for Cross compile on ubuntu-latest

- build-resources/opaque-types/src/lib.rs
Fixes compilation after shm provider size changed
> Fix dummy shm provider definition

- Cargo.lock
- build-resources/opaque-types/Cargo.lock
- include/zenoh_commons.h
- src/publication_cache.rs
Sister PR to account for api changes due to https://github.com/eclipse-zenoh/zenoh/pull/1792
> support for api changes in namespaces PR

- .github/workflows/release.yml
ubuntu-20.04 runners are being deprecated.
> chore: update ubuntu runners to ubuntu-24.04

- .github/workflows/ci.yml
Fix CI error https://github.com/eclipse-zenoh/zenoh-c/actions/runs/14200029767/job/39784479557?pr=971
> replaced ~ to $HOME in CI as the ~ doesn't always work

- tests/z_api_liveliness.c
> fix z_api_liveliness_test

- build.rs
> build.rs lint fix

- .gitignore
- build.rs
- buildrs/cbindgen_generator.rs
- buildrs/opaque_types_generator.rs
- src/opaque_types/mod.rs
do not build opaque types in source tree
> do not build opaque types in source tree

- docs/api.rst
> add missing functions to docs

- src/collections.rs
- src/config.rs
- src/encoding.rs
- src/get.rs
- src/keyexpr.rs
- src/lib.rs
- src/querier.rs
- src/serialization.rs
- src/zbytes.rs
fix strlen calls on null pointers
> fix strlen calls on null pointers

- Cargo.lock
- build-resources/opaque-types/Cargo.lock
- build-resources/opaque-types/src/lib.rs
- examples/CMakeLists.txt
- examples/z_pub.c
- examples/z_pub_shm.c
- examples/z_querier.c
- include/zenoh_commons.h
- src/closures/mod.rs
- src/commons.rs
- src/lib.rs
- src/matching.rs
- src/publication_cache.rs
- src/publisher.rs
- src/querier.rs
- src/queryable.rs
- src/querying_subscriber.rs
- src/subscriber.rs
stabilize querier;
stabilize matching listener/status;
stabilize locality;
> stabilize querier, matching and locality
